# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e0e55bae1c048b6bb385373a5b81225f1545e029548f83e3bf482732a6629aa1aaea8ad3447c5de25384641ea6be76ff43b45cd5abc9483bd3edc62e3f2c05a

test:
  secret_key_base: 4353b995ad939fb63a35eb6c0a400db02e69148e7c99296ecea08632d0685e7717455b7903f142e4d14d698d1359e754a473762df013eb19ad2a818fee5de444

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
